spring:
  application:
    name: ribbon-demo

server:
  port: 8090

# stores 是自定义的
stores:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000